name: CI/CD Pipeline
 
on:

  push:

    branches:

      - main
 
jobs:

  build:

    runs-on: ubuntu-latest
 
    steps:

    - name: Checkout code

      uses: actions/checkout@v2
 
    - name: Login to Azure Container Registry

      uses: azure/docker-login@v1

      with:

        login-server: ${{ secrets.AZURE_REGISTRY_URL }}

        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}

        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
 
    - name: push nginx image

      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_URL }}/nginx:v1 .
        docker push ${{ secrets.AZURE_REGISTRY_URL }}/nginx:v1
 
