name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Triggers the action when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Triggers the action when a PR is created for 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t your-dockerhub-username/your-app-name .
          docker push your-dockerhub-username/your-app-name

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          kubeconfig: ${{ secrets.AKS_KUBECONFIG }}

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl set image deployment/your-deployment your-container=your-dockerhub-username/your-app-name:latest
