name: CI/CD Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write   # ✅ Required for OIDC
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # ---------------------- Azure Login with OIDC ----------------------
    - name: Azure login (OIDC)
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        

    - name: Set image variables
      run: |
        echo "IMAGE_NAME=acrdemooidc.azurecr.io/nginx" >> $GITHUB_ENV
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    # ---------------------- Build and Push Docker Image ----------------------
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrdemooidc.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./nginx.dockerfile .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Logout from Azure Container Registry
      run: docker logout acrdemooidc.azurecr.io

    # ---------------------- Update Manifest ----------------------
    - name: Replace image in nginx.yml(deployment.yml)
      run: |
        echo "Updating nginx.yml with image: $IMAGE_NAME:$IMAGE_TAG"
        sed -i "s|image: .*|image: $IMAGE_NAME:$IMAGE_TAG|g" nginx.yml
    - name: Verify updated nginx.yml
      run: cat nginx.yml
 # ---------------------- Commit updated manifest back to repo ----------------------
    - name: Commit updated nginx.yml back to repo
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git pull origin main
        git add nginx.yml
        git commit -m "Auto-update nginx.yml with image $IMAGE_NAME:$IMAGE_TAG" || echo "No changes to commit"
        git push origin main

    # ---------------------- Deploy to AKS ----------------------
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group demorg --name akscluster --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f nginx.yml
