name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # This triggers the pipeline on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.AZURE_REGISTRY_URL }}
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.AZURE_REGISTRY_URL }}/nginx:v1 .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.AZURE_REGISTRY_URL }}/nginx:v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Flux CLI
      uses: fluxcd/flux2-action@v2
      with:
        version: 'latest'

    - name: Apply Flux Kustomization
      run: |
        flux reconcile kustomization my-app --namespace=default
