name: CI/CD Pipeline

on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set image variables
      run: |
        echo "IMAGE_NAME=acrdemooidc.azurecr.io/nginx" >> $GITHUB_ENV
        echo "IMAGE_TAG=latest" >> $GITHUB_ENV

    # ---------------------- Build and Push Docker Image ----------------------
    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: acrdemooidc.azurecr.io
        username: ${{ secrets.AZURE_REGISTRY_USERNAME }}
        password: ${{ secrets.AZURE_REGISTRY_PASSWORD }}

    - name: Build and push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t $IMAGE_NAME:$IMAGE_TAG -f ./nginx.dockerfile .
        docker push $IMAGE_NAME:$IMAGE_TAG

    - name: Logout from Azure Container Registry
      run: docker logout containernginx.azurecr.io

    # ---------------------- Update Manifest ----------------------
    - name: Replace image in nginx.yml
      run: |
        echo "Updating nginx.yml with image: $IMAGE_NAME:$IMAGE_TAG"
        sed -i "s|containernginx.azurecr.io/nginx:v1|$IMAGE_NAME:$IMAGE_TAG|g" nginx.yml

    # ---------------------- Deploy to AKS ----------------------
    - name: Azure login
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Get AKS credentials
      run: az aks get-credentials --resource-group demorg --name akscluster --overwrite-existing

    - name: Deploy to AKS
      run: |
        kubectl apply -f nginx.yml
